// trycatch a prueba de errores
// situaciones: usuario no puedo iniciar sesión, conexión a bd, pago se pudo completar
const numero1 = 20;
const numero2 = 40;

console.log(numero1);

try {
  console.log(numero3);
} catch (error) {
  console.log(error);
}
console.log(numero2);
